Map<String, String> localizationMapAr = {
  "title": "Cowpay",
  "quarterTurns": "2",
  "fontFamily": "GeFlow",
  "anotherFontFamily": "Cairo",
  "paymentMethod": "طرق الدفع",
  "paymentDetails": "تفاصيل الدفع",
  "addPaymentCard": "أضف بطاقة الدفع",
  "noPyamentMethodsAvailable": "لا توجد طرق دفع",
  "emptyData": "لا توجد بيانات",
  "next": "التالي",
  "somethingWentWrong": "حدث خطأ!",
  "invalidCardNumber": "رقم البطاقة غير صحيح",
  "requiredCardNumber": "رقم البطاقة مطلوب",
  "requiredCardExpiry": "تاريخ انتهاء الصلاحية مطلوب",
  "invalidCardExpiry": "تاريخ انتهاء الصلاحية غير صحيح",
  "requiredCardHolderName": "الأسم مطلوب",
  "invalidCardHolderName": "الأسم غير صحيح",
  "requiredCardCvv": "رمز التحقق مطلوب",
  "invalidCardCvv": "رمز التحقق غير صحيح",
  "cardHolderName": "اسم صاحب البطاقة",
  "cardNumber": "رقم البطاقة",
  "expiryDate": "تاريخ الانتهاء",
  "cvv": "رمز التحقق",
  "totalPaymentAmount": "المبلغ الإجمالي",
  "saveThisCardInformationForFasterPayment": "حفظ البطاقة للمعاملات اللاحقة",
  "currency": "جم",
  "subtotal": "المبلغ الاساسي:",
  "vat": "ضريبة القيمة المضافة:",
  "fees": "مصاريف الخدمة:",
  "pay": "دفع",
  "savedCards": "البطاقات المحفوظة",
  "addNewCard": "اضافة بطاقة جديدة",
  "invalidCardExpiryOldDate": "تاريخ انتهاء الصلاحية غير صحيح",
  "close": "إغلاق",
  "discount": "الخصم",
  "shippingFees": "رسوم الشحن",
  "requiredMobileNumber": "رقم الهاتف مطلوب",
  "invalidMobileNumber": "رقم الهاتف يجب أن يتكون من 11 رقما يبدأ ب 01",
  "mobileNumber": "رقم الهاتف المحمول",
  "fawryCodeMessage": "استخدم هذا الكود لاستكمال عملية الدفع عن طريق فوري",
  "copied": "تم النسخ",
  "selectPaymentMethod": "اختر طريقة الدفع",
  "selectCard": "اختر البطاقة",
  "typeCardCvvNumber": "ادخل رمز التحقق",
  "payNow": "ادفع الآن",
  "saveCards": "البطاقات المحفوظة",
  "exit": "خروج",
  "retry": "إعادة المحاولة",
  "youAreAboutToExitPayment": "انت على وشك مغادرة صحفة الدفع",
  "paymentFailed": "فشل محاولة الدفع",
  "successPayment": "تم الدفع بنجاح",
  "referenceNumber": "الرقم المرجعي",
  "creditCard": "بطاقة ائتمان",
  "fawry": "فوري",
  "enterYourMobileNumber":"ادخل رقم الهاتف"
};
