Map<String, String> localizationMapAr = {
  "title": "Cowpay",
  "quarterTurns": "2",
  "fontFamily": "GeFlow",
  "anotherFontFamily": "Cairo",
  "paymentMethod": "طريقة الدفع",
  "paymentDetails": "تفاصيل الدفع",
  "addPaymentCard": "إضافة بطاقة دفع",
  "noPyamentMethodsAvailable": "لا توجد طرق دفع متاحة",
  "emptyData": "مسح البيانات",
  "next": "التالي",
  "somethingWentWrong": "حدث خطأ",
  "invalidCardNumber": "رقم البطاقة غير صالح",
  "requiredCardNumber": "رقم البطاقة مطلوب",
  "requiredCardExpiry": "تاريخ انتهاء البطاقة مطلوب",
  "invalidCardExpiry": "تاريخ الانتهاء غير صالح",
  "requiredCardHolderName": "اسم صاحب البطاقة مطلوب",
  "invalidCardHolderName": "اسم صاحب البطاقة غير صالح",
  "requiredCardCvv": "الرقم السري للبطاقة مطلوب",
  "invalidCardCvv": "الرقم السري غير صالح",
  "cardHolderName": "اسم صاحب البطاقة",
  "cardNumber": "رقم البطاقة",
  "expiryDate": "تاريخ الانتهاء",
  "cvv": "الرقم السري",
  "totalPaymentAmount": "إجمالي المبلغ المدفوع",
  "saveThisCardInformationForFasterPayment": "حفظ بيانات البطاقة لمعاملات أسرع",
  "currency": "جنيه مصري",
  "subtotal": "المجموع الفرعي : ",
  "vat": "ضريبة القيمة المضافة : ",
  "fees": "الرسوم : ",
  "pay": "دفع",
  "savedCards": "البطاقات المحفوظة",
  "addNewCard": "إضافة بطاقة جديدة",
  "invalidCardExpiryOldDate": "صلاحية البطاقة منتهية",
  "close": "إغلاق",
  "discount": "الخصم",
  "shippingFees": "مصاريف الشحن",
  "requiredMobileNumber": "رقم الهاتف مطلوب",
  "invalidMobileNumber": "رقم الهاتف غير صالح",
  "mobileNumber": "رقم الهاتف",
  "fawryCodeMessage": "استخدم هذا الكود لإتمام عملية الدفع عن طريق فوري",
  "copied": "تم النسخ",
  "selectPaymentMethod": "اختر طريقة الدفع",
  "selectCard": "اختر البطاقة",
  "typeCardCvvNumber": "ادخل الرقم السري للبطاقة",
  "payNow": "ادفع الآن",
  "saveCards": "البطاقات المحفوظة",
  "exit": "خروج",
  "retry": "إعادة المحاولة",
  "youAreAboutToExitPayment": "أنت على وشك مغادرة صفحة الدفع",
  "paymentFailed": "فشل محاولة الدفع",
  "successPayment": "تم الدفع بنجاح",
  "referenceNumber": "رقم الطلب",
  "fawry_pay": "فوري",
  "credit_card": "بطاقة ائتمان",
  "bank_card": "بطاقة بنكية"
};
