Map<String, String> localizationMapAr = {
  "title": "Cowpay",
  "quarterTurns": "2",
  "fontFamily": "GeFlow",
  "anotherFontFamily": "Cairo",
  "paymentMethod": "	الدفع طريقة ",
  "paymentDetails": "	الدفع تفاصيل ",
  "addPaymentCard": "	الدفع بطاقة أضف ",
  "noPyamentMethodsAvailable": "	دفع طرق لا توجد ",
  "emptyData": "	بيانات	لا توجد ",
  "next": "	التالي ",
  "somethingWentWrong": "	خطأ حدث !",
  "invalidCardNumber": "	غير صحيح	البطاقة	رقم ",
  "requiredCardNumber": "	مطلوب رقم البطاقة	",
  "requiredCardExpiry": "	مطلوب البطاقة	انتهاء	تاريخ ",
  "invalidCardExpiry": "	صحيح غير انتهاء	تاريخ ",
  "requiredCardHolderName": "	 مطلوب صاحب البطاقة	اسم",
  "invalidCardHolderName": "	صحيح غير البطاقة	اسم صاحب	",
  "requiredCardCvv": "مطلوب من البطاقة	التحقق	رقم",
  "invalidCardCvv": "	غير صحيح	رقم تحقق	",
  "cardHolderName": "	البطاقة	اسم صاحب	",
  "cardNumber": "	رقم البطاقة 	",
  "expiryDate": "	الانتهاء	تاريخ ",
  "cvv": "	رقم التحقق 	",
  "totalPaymentAmount": "	الإجمالي	المبلغ ",
  "saveThisCardInformationForFasterPayment":
      " أسرع دفع لعمليات	البطاقة	هذه احفظ بيانات	",
  "currency": "	جنيه مصري 	",
  "subtotal": "	الفرعي	المجموع	: ",
  "vat": "	المضافة	القيمة	ضريبة : ",
  "fees": "	الرسوم	: ",
  "pay": "	دفع ",
  "savedCards": "	المحفوظة 	البطاقات	",
  "addNewCard": "	جديدة بطاقة أضف ",
  "invalidCardExpiryOldDate": "	منتهي الصلاحية	تاريخ ",
  "close": "	إغلاق ",
  "discount": "	الخصم ",
  "shippingFees": "	رسوم الشحن 	",
  "requiredMobileNumber": "	مطلوب المحمول	رقم الهاتف	",
  "invalidMobileNumber": "	غير صحيح	المحمول	الهاتف	رقم ",
  "mobileNumber": "	المحمول	رقم الهاتف	",
  "fawryCodeMessage": "	فوري عن طريق	الدفع لاستكمال	الكود هذا استخدم ",
  "copied": "	النسخ تم ",
  "selectPaymentMethod": "	الدفع اختر طريقة	",
  "selectCard": "	البطاقة	اختر ",
  "typeCardCvvNumber": "	البطاقة	رقم تحقق	ادخل ",
  "payNow": "	الآن ادفع ",
  "saveCards": "	المحفوظة 	البطاقات	",
  "exit": "	خروج ",
  "retry": "	المحاولة	إعادة ",
  "youAreAboutToExitPayment": "	صفحة الدفع	من وشك الخروج	أنت على	",
  "paymentFailed": "	الدفع فشل محاولة	",
  "successPayment": "	الدفع بنجاح	تم ",
  "referenceNumber": "	المرجعي	الرقم "
};
