Map<String, String> localizationMapEn = {
  "title": "Cowpay",
  "quarterTurns": "0",
  "fontFamily": "Poppins",
  "anotherFontFamily": "GeFlow",
  "paymentMethod": "Payment Method",
  "paymentDetails": "Payment Details",
  "addPaymentCard": "Add Payment Card",
  "noPyamentMethodsAvailable": "No payment methods Available",
  "emptyData": "Empty Data",
  "next": "Next",
  "somethingWentWrong": "Something went wrong",
  "invalidCardNumber": "Invalid Card Number",
  "requiredCardNumber": "Required Card Number",
  "requiredCardExpiry": "Required Card Expiry",
  "invalidCardExpiry": "Invalid Card Expiry",
  "requiredCardHolderName": "Required Card Holder Name",
  "invalidCardHolderName": "Invalid Card Holder Name",
  "requiredCardCvv": "Required Card Cvv",
  "invalidCardCvv": "Invalid Card Cvv",
  "cardHolderName": "Card Holder Name",
  "cardNumber": "Card Number",
  "expiryDate": "Expiry Date",
  "cvv": "cvv",
  "totalPaymentAmount": "Total Payment Amount",
  "saveThisCardInformationForFasterPayment":
      "Save this card information for faster payment",
  "currency": "EGP",
  "subtotal": "Subtotal : ",
  "vat": "Vat : ",
  "fees": "Fees : ",
  "pay": "Pay",
  "savedCards": "Saved Cards",
  "addNewCard": "Add New Card",
  "invalidCardExpiryOldDate": "Date is expired",
  "close": "Close",
  "discount": "Discount",
  "shippingFees": "Shipping Fees",
  "requiredMobileNumber": "Required Mobile Number",
  "invalidMobileNumber": "Invalid Mobile Number",
  "mobileNumber": "Mobile Number",
  "fawryCodeMessage": "Use this code to complete your payment with Fawry",
  "copied": "Copied",
  "selectPaymentMethod": "Select Payment method",
  "selectCard": "Select Card",
  "typeCardCvvNumber": "Type card CVV number",
  "payNow": "Pay Now",
  "saveCards": "Saved Cards",
  "exit": "Exit",
  "retry": "Retry",
  "youAreAboutToExitPayment": "You are about to exit from your payment",
  "paymentFailed": "Payment had been failed",
  "successPayment": "Payment is successfully done",
  "referenceNumber": "Reference Number"
};
